server:
  port: 8001

spring:
  datasource:
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      type: com.alibaba.druid.pool.DruidDataSource
      #druid:
      max-wait: 100000
      max-active: 20
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot_mybatis_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      type: com.alibaba.druid.pool.DruidDataSource
      #druid:
      max-wait: 300000
      max-active: 50
      query-timeout: 10
      validation-query: SELECT 1

# 打开sql日志
logging:
  level:
    com.wyx.springbootmybatis.mapper.read: debug
    com.wyx.springbootmybatis.mapper.write: debug

# mybatis分页配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql